export enum ProductCategory{
        beauty="beauty",
        fragrances ="fragrances",
        furniture = "furniture",
        groceries = "groceries",
        home_decoration ="home-decoration",
        kitchen_accessories ="kitchen-accessories",
        laptops = "laptops",
        mens_shirts = "mens-shirts",
        mens_shoes = "mens-shoes",
        mens_watches = "mens-watches",
        mobile_accesories = "mobile-accessories",
        motorcycle = "motorcycle",
        skin_care = "skin-care",
        smartphones = "smartphones",
        sprts_accesories = "sports-accessories",
        sunglasses = "sunglasses",
        tablets ="tablets",
        tops ="tops",
        vehicle ="vehicle",
        womens_bags = "womens-bags",
        womens_dresses = "womens-dresses",
        womens_jewellery = "womens-jewellery",
        womens_shoes = "womens-shoes",
        womens_watches = "womens-watches"
}